#!/bin/bash
#
# Regenerates src/fontIds.h from the built-in font headers.
#
#   ./lib/EpdFont/scripts/build-font-ids.sh > src/fontIds.h
#
# A font ID is just a stable, non-zero token used as the renderer's font-map
# key. It is derived from the font data so that regenerating a font changes its
# ID, which in turn invalidates the section caches that record spec.fontId
# (lib/Epub/Epub/Section.cpp:97,153) -- a re-layout is required whenever the
# glyphs change.
#
# Uses python3 (already required by scripts/gen_i18n.py and scripts/build_html.py)
# rather than ruby, so it runs anywhere the firmware builds.

set -e

cd "$(dirname "$0")/../builtinFonts"

python3 - <<'PY'
import hashlib

# name -> font header files whose contents determine the ID.
# Both reader families get IDs even though a build links only one (see
# builtinFonts/all.h); these are just compile-time constants.
FONTS = [(f"{family.upper()}_{size}", [f"{family}_{size}_{style}.h"
                                       for style in ("regular", "bold", "bolditalic", "italic")])
         for family in ("bitter", "notoserif")
         for size in (12, 14, 16, 18)]
FONTS += [
    ("UI_10", ["ubuntu_10_regular.h", "ubuntu_10_bold.h"]),
    ("UI_12", ["ubuntu_12_regular.h", "ubuntu_12_bold.h"]),
    ("SMALL", ["notosans_8_regular.h"]),
]


def font_id(paths):
    total = sum(int(hashlib.sha256(open(p, "rb").read()).hexdigest(), 16) for p in paths)
    return total % (2 ** 32) - (2 ** 31)


print("// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh")
print("#pragma once")
print()
for name, paths in FONTS:
    print(f"#define {name}_FONT_ID ({font_id(paths)})")
print()
print('// Font ID 0 is reserved as the "not found" sentinel.')
print("// Guard against any hash accidentally producing 0.")
for name, _ in FONTS:
    print(f'static_assert({name}_FONT_ID != 0, "Font ID collision with sentinel");')
PY
